# Form implementation generated from reading ui file 'Message_Box.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messageFrame = QtWidgets.QFrame(self.centralwidget)
        self.messageFrame.setGeometry(QtCore.QRect(430, 500, 341, 81))
        self.messageFrame.setStyleSheet("")
        self.messageFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.messageFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.messageFrame.setObjectName("messageFrame")
        self.messageContainer = QtWidgets.QFrame(self.messageFrame)
        self.messageContainer.setGeometry(QtCore.QRect(-1, 10, 341, 61))
        self.messageContainer.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border-radius: 15px;\n"
"}")
        self.messageContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.messageContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.messageContainer.setObjectName("messageContainer")
        self.errorIcon = QtWidgets.QLabel(self.messageContainer)
        self.errorIcon.setGeometry(QtCore.QRect(16, 14, 32, 32))
        self.errorIcon.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}    ")
        self.errorIcon.setText("")
        self.errorIcon.setPixmap(QtGui.QPixmap("assets/img/error.png"))
        self.errorIcon.setScaledContents(True)
        self.errorIcon.setObjectName("errorIcon")
        self.errorText = QtWidgets.QLabel(self.messageContainer)
        self.errorText.setGeometry(QtCore.QRect(66, 10, 261, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.errorText.setFont(font)
        self.errorText.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"    color: rgba(255, 255, 255, 0.8)\n"
"}")
        self.errorText.setObjectName("errorText")
        self.closeMsgIcon = QtWidgets.QLabel(self.messageContainer)
        self.closeMsgIcon.setGeometry(QtCore.QRect(318, 9, 8, 8))
        self.closeMsgIcon.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.closeMsgIcon.setText("")
        self.closeMsgIcon.setPixmap(QtGui.QPixmap("assets/img/close.png"))
        self.closeMsgIcon.setScaledContents(True)
        self.closeMsgIcon.setObjectName("closeMsgIcon")
        self.closeMsgButton = QtWidgets.QPushButton(self.messageContainer)
        self.closeMsgButton.setGeometry(QtCore.QRect(318, 9, 8, 8))
        self.closeMsgButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.closeMsgButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}")
        self.closeMsgButton.setText("")
        self.closeMsgButton.setObjectName("closeMsgButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.errorText.setText(_translate("MainWindow", "An Unknown Error Occurred. Please try again."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
